name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Debug
        run: |
          pwd
          ls

      - name: Change to lambda-functions directory
        run: cd lambda 

      - name: Debug
        run: |
          pwd
          ls

      - name: Deploy Lambda Functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          for file in lambda-functions/*.js; do
            function_name=$(basename "$file" .js)
            aws lambda create-function \
              --function-name $function_name \
              --runtime nodejs14.x \
              --role arn:aws:iam::533267423509:role/lambda-s3-dyanmodb-full-access \
              --handler ${function_name}.handler \
              --code "fileb://${file}"
          done
