name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # - name: Debug
      #   run: |
      #     pwd
      #     ls

      # - name: Change to lambda-functions directory
      #   run: cd lambda

      # - name: Debug
      #   run: |
      #     pwd
      #     ls

      - name: Deploy Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          file="sum.js"
          function_name=$(basename "$file" .js)
          aws lambda create-function \
            --function-name $function_name \
            --code "fileb://${GITHUB_WORKSPACE}/${file}"
